apiVersion: v1
kind: Service
metadata:
  name: tomcatt-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80   # Expose on port 80
      targetPort: 8080  # Target Tomcat's internal port
  type: NodePort
